// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbsetfor_Custometradded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbsetfor_Custometradded));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280605174_dbsetfor_Custometradded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
